network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
    eth1:
      dhcp4: no
      dhcp6: no
  bridges:
    br0:
      interfaces: [eth0, eth1]
      addresses:
        - 10.200.0.1/20
      nameservers:
        addresses:
          - 127.0.0.1
          - 8.8.8.8
      dhcp4: no
      dhcp6: no

